matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8.3
before_install:
  - brew update
  - brew install carthage
  - carthage bootstrap --platform ios
script:
  - set -o pipefail
  - xcodebuild test -scheme RxInstantiate -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" | xcpretty -c
